import { StyleSheet } from 'react-native';

import { theme } from '@/src/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background.main,
  },
  topButtons: {
    position: 'absolute',
    top: theme.spacing.spacing15,
    left: theme.spacing.spacing5,
    right: theme.spacing.spacing5,
    zIndex: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  backButton: {
    backgroundColor: theme.colors.white,
    borderRadius: theme.spacing.spacing5,
    padding: theme.spacing.spacing2,
    shadowColor: theme.colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  contentContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: theme.spacing.spacing5,
  },
  headerText: {
    fontSize: theme.typography.fontSize.font7,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.text.main,
    textAlign: 'center',
    marginTop: theme.spacing.spacing12,
  },
  highlightedText: {
    color: theme.colors.blue[500],
  },
  imageContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: theme.spacing.spacing5,
  },
  geminiImage: {
    width: '100%',
    maxWidth: 350,
    height: 400,
  },
  createButton: {
    backgroundColor: theme.colors.blue[500],
    borderRadius: theme.spacing.spacing3,
    paddingVertical: theme.spacing.spacing4,
    paddingHorizontal: 130,
    flexDirection: 'row',
    marginBottom: theme.spacing.spacing2,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    shadowColor: theme.colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  createButtonText: {
    fontSize: theme.typography.fontSize.font4,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.text.white,
    marginLeft: theme.spacing.spacing2,
  },
  joinButton: {
    backgroundColor: theme.colors.white,
    borderWidth: 2,
    borderColor: theme.colors.blue[500],
    borderRadius: theme.spacing.spacing3,
    paddingVertical: theme.spacing.spacing4,
    paddingHorizontal: 130,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    shadowColor: theme.colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
    marginBottom: theme.spacing.spacing6,
  },
  joinButtonText: {
    fontSize: theme.typography.fontSize.font4,
    fontWeight: theme.typography.fontWeight.bold,
    color: theme.colors.blue[500],
    marginLeft: theme.spacing.spacing2,
  },
});
