import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  backButton: {
    position: 'absolute',
    top: 60,
    left: 20,
    zIndex: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 20,
    padding: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  contentContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  headerText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#000000',
    textAlign: 'center',
    marginTop: 50,
  },
  highlightedText: {
    color: '#3488FF', // 삼쩜삼의 포인트 컬러 (파란색)
  },
  imageContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  geminiImage: {
    width: '100%',
    maxWidth: 350,
    height: 400,
  },
  footer: {
    paddingHorizontal: 20,
    paddingBottom: 20,
    marginTop: -30,
  },
  createButton: {
    backgroundColor: '#4A9EFF',
    borderRadius: 12,
    paddingVertical: 15,
    paddingHorizontal: 130,
    flexDirection: 'row',
    marginBottom: 8,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  createButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginLeft: 10,
  },
  joinButton: {
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#4A9EFF',
    borderRadius: 12,
    paddingVertical: 15,
    paddingHorizontal: 130,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
    marginBottom: 24,
  },
  joinButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#4A9EFF',
    marginLeft: 10,
  },
});
